backend:
  name: github
  repo: alberto56/presentation_docker_en
  branch: gh-pages
  base_url: https://app.staticauth.com
  auth_endpoint: /auth/github/repo/696663c98a3239f2047175fc
media_folder: static/uploads
public_folder: /uploads
collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    slug: '{{slug}}'
    fields:
      - label: Title
        name: title
        widget: string
      - label: Date
        name: date
        widget: datetime
      - label: Body
        name: body
        widget: markdown
